name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

  # Run tests for all PRs targeting `main`
  pull_request:
    branches:
      - main

jobs:
  the_job:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.3.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: mrandri19/recsys2021-submission-image:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
